name: Tesla Logger & Report

on:
  schedule:
    - cron: "*/30 * * * *"   # ogni 30 minuti (UTC)
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      TZ: Europe/Rome
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Compute date key (Europe/Rome)
        run: echo "DATE=$(TZ=Europe/Rome date +%F)" >> "$GITHUB_ENV"

      - name: Restore state cache (tokens, contatori, log)
        uses: actions/cache@v4
        with:
          path: .runner_state
          key: tesla-state-${{ env.DATE }}
          restore-keys: |
            tesla-state-

      - name: Ensure state dir
        run: mkdir -p .runner_state

      - name: Create .env from secrets + config
        run: |
          cat > .env <<'EOF'
          TESLA_CLIENT_ID=${{ secrets.TESLA_CLIENT_ID }}
          TESLA_CLIENT_SECRET=${{ secrets.TESLA_CLIENT_SECRET }}
          TESLA_REGION=eu
          TESLA_REDIRECT_URI=${{ secrets.TESLA_REDIRECT_URI }}
          TESLA_VEHICLE_TAG=${{ secrets.TESLA_VEHICLE_TAG }}

          EXTRA_SCOPES=vehicle_cmds
          WAKE_POLICY=onfail
          QUIET_WINDOW=00:00-07:30
          MAX_WAKE_PER_DAY=16

          LOG_FILE=.runner_state/tesla_soc.jsonl
          DAILY_WAKE_FILE=.runner_state/wake_counter.json
          TOKENS_PATH=.runner_state/tokens.json
          STATE_PATH=.runner_state/state.json

          AUTO_PARTNER_REGISTER=true
          TESLA_PARTNER_DOMAIN=${{ secrets.TESLA_PARTNER_DOMAIN }}
          TESLA_PARTNER_CLIENT_ID=${{ secrets.TESLA_PARTNER_CLIENT_ID }}
          TESLA_PARTNER_CLIENT_SECRET=${{ secrets.TESLA_PARTNER_CLIENT_SECRET }}
          EOF

      - name: Seed refresh token (solo al primo run)
        run: |
          if [ ! -f .runner_state/tokens.json ]; then
            if [ -z "${{ secrets.TESLA_REFRESH_TOKEN }}" ]; then
              echo "TESLA_REFRESH_TOKEN secret mancante"; exit 1
            fi
            echo '{ "refresh_token": "'"${{ secrets.TESLA_REFRESH_TOKEN }}"'", "created_at": '"$(date +%s)"' }' > .runner_state/tokens.json
          else
            echo "tokens.json ripristinato dalla cache."
          fi

      - name: Run logger
        run: npm run log

      - name: Count samples in log
        id: count
        shell: bash
        run: |
          if [ -f .runner_state/tesla_soc.jsonl ]; then
            count=$(grep -c '"soc_percent":' .runner_state/tesla_soc.jsonl || true)
          else
            count=0
          fi
          echo "Found samples: $count"
          echo "count=$count" >> "$GITHUB_OUTPUT"

      - name: Build placeholder report (first run)
        if: ${{ fromJson(steps.count.outputs.count) < 2 }}
        shell: bash
        run: |
          echo "Meno di 2 letture: costruisco un report segnaposto."
          mkdir -p dist
          cat > dist/index.html <<'HTML'
          <!doctype html>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width,initial-scale=1">
          <title>Tesla — Report in preparazione</title>
          <style>
            body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:32px;color:#111}
            .card{border:1px solid #e6e6e6;border-radius:12px;padding:18px;max-width:720px}
            h1{margin:0 0 8px}
            .muted{color:#666}
            code{background:#f6f6f6;padding:2px 6px;border-radius:6px}
          </style>
          <div class="card">
            <h1>Report in preparazione</h1>
            <p class="muted">Servono almeno <b>2</b> letture per disegnare i grafici.</p>
            <p>Il logger è attivo. Al prossimo run troverai il report completo qui.</p>
          </div>
          HTML
          cp .runner_state/tesla_soc.jsonl dist/ || true
          echo "day;delta_soc_pts;soc_first;soc_last;soc_min;soc_max" > dist/daily_summary.csv

      - name: Run analyzer (build site)
        if: ${{ fromJson(steps.count.outputs.count) >= 2 }}
        shell: bash
        run: |
          npm run report
          mkdir -p dist
          mv index.html dist/
          cp .runner_state/tesla_soc.jsonl dist/
          cp daily_summary.csv dist/

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: tesla-report
          path: dist

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
